### ISSUE TITLE
World Generation becomes stuck after cancelling previous world gen

### ISSUE THREAD

**Issue by brianzooming** [JavidPack/WorldGenPreviewer#17]
i reported this in tmodloader but it turns out to be worldgenpreviewer. when generating worlds with the preview mod and no any other mod on it only generates mud and dungeon on the left side after generating a world and canceling. Even with the preview mod when the error occurs i cannot exit the game and is forced to close it on steam. the multiplayer one was just discovered. the first three images are about world gen and the last is the message that appears after multiplayer crash
<img width="1280" alt="Screenshot (108)" src="https://github.com/JavidPack/WorldGenPreviewer/assets/145192949/6ca82a90-1db8-4a25-bbb4-18c008f79f61">
<img width="1280" alt="Screenshot (109)" src="https://github.com/JavidPack/WorldGenPreviewer/assets/145192949/de47fb4b-4ff2-49dd-aab2-e301065bf066">
<img width="1280" alt="Screenshot (110)" src="https://github.com/JavidPack/WorldGenPreviewer/assets/145192949/20a3abcb-6d7a-4642-81ad-784a84e47a8c">
<img width="686" alt="Screenshot (111)" src="https://github.com/JavidPack/WorldGenPreviewer/assets/145192949/0fbd7a46-35d0-4eff-a0f2-2a72d075a0bf">
Steps to reproduce
generate a world and leave using the preview mod (i use that to get a good world to play on)(the first world is normal)
generate another world
stuck after world only generating mud and dungeon (world gen stopped)

**Comment by JavidPack** [comment]
Thanks for the report.
